// src/renderer/src/utils/sharepointTemplates.ts
// Templates HTML for trips and vacations to save in SharePoint

import type { Task } from '../types'

// ─────────────────────────────────────────
// TEMPLATE GENERATORS
// ─────────────────────────────────────────

interface TripData {
  name: string
  person: string
  startDate: string
  endDate: string
  description: string
}

interface VacationData {
  person: string
  type: 'sick-day' | 'pto' | 'compensation' | 'birthday'
  days: number
  startDate: string
  endDate: string
}

function formatDate(dateStr: string): string {
  if (!dateStr) return '—'
  const date = new Date(dateStr)
  if (isNaN(date.getTime())) return dateStr
  return date.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}

function getVacationTypeLabel(type: string): string {
  const labels: Record<string, string> = {
    'sick-day': 'Sick Day',
    'pto': 'PTO (Paid Time Off)',
    'compensation': 'Compensation Day',
    'birthday': 'Birthday'
  }
  return labels[type] || type
}

/**
 * Generates HTML content for a Trip
 */
export function generateTripHTML(data: TripData): string {
  const duration = calculateDays(data.startDate, data.endDate)
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Trip: ${escapeHtml(data.name)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f5f5f5;
      padding: 20px;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      background: white;
      border-radius: 12px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #378ADD 0%, #2a6bc0 100%);
      color: white;
      padding: 40px 30px;
    }
    .header h1 {
      font-size: 28px;
      font-weight: 600;
      margin-bottom: 8px;
    }
    .header .subtitle {
      font-size: 14px;
      opacity: 0.9;
    }
    .content {
      padding: 30px;
    }
    .field {
      margin-bottom: 24px;
    }
    .field-label {
      font-size: 11px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #666;
      margin-bottom: 6px;
    }
    .field-value {
      font-size: 16px;
      color: #333;
    }
    .field-value.large {
      font-size: 20px;
      font-weight: 500;
    }
    .dates-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
    }
    .description-box {
      background: #f8f9fa;
      border-radius: 8px;
      padding: 16px;
      white-space: pre-wrap;
      min-height: 100px;
    }
    .footer {
      border-top: 1px solid #eee;
      padding: 20px 30px;
      background: #fafafa;
      font-size: 12px;
      color: #999;
      text-align: center;
    }
    @media print {
      body { background: white; }
      .container { box-shadow: none; }
    }
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>${escapeHtml(data.name)}</h1>
      <div class="subtitle">Trip Details</div>
    </header>
    
    <div class="content">
      <div class="field">
        <div class="field-label">Trip Name</div>
        <div class="field-value large">${escapeHtml(data.name)}</div>
      </div>
      
      <div class="field">
        <div class="field-label">Traveler</div>
        <div class="field-value large">${escapeHtml(data.person)}</div>
      </div>
      
      <div class="dates-grid">
        <div class="field">
          <div class="field-label">Start Date</div>
          <div class="field-value">${formatDate(data.startDate)}</div>
        </div>
        <div class="field">
          <div class="field-label">End Date</div>
          <div class="field-value">${formatDate(data.endDate)}</div>
        </div>
      </div>
      
      <div class="field">
        <div class="field-label">Duration</div>
        <div class="field-value">${duration} day${duration !== 1 ? 's' : ''}</div>
      </div>
      
      <div class="field">
        <div class="field-label">Description</div>
        <div class="description-box">${data.description ? escapeHtml(data.description) : '<em style="color: #999;">No description provided</em>'}</div>
      </div>
    </div>
    
    <footer class="footer">
      Generated by NPD Planner • ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
    </footer>
  </div>
</body>
</html>`
}

/**
 * Generates HTML content for a Vacation
 */
export function generateVacationHTML(data: VacationData): string {
  const hours = data.days * 8
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Time Off: ${escapeHtml(data.person)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #333;
      background: #f5f5f5;
      padding: 20px;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      background: white;
      border-radius: 12px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.1);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #D4537E 0%, #b83d66 100%);
      color: white;
      padding: 40px 30px;
    }
    .header h1 {
      font-size: 24px;
      font-weight: 600;
      margin-bottom: 8px;
    }
    .header .subtitle {
      font-size: 14px;
      opacity: 0.9;
    }
    .content {
      padding: 30px;
    }
    .field {
      margin-bottom: 24px;
    }
    .field-label {
      font-size: 11px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #666;
      margin-bottom: 6px;
    }
    .field-value {
      font-size: 16px;
      color: #333;
    }
    .field-value.large {
      font-size: 20px;
      font-weight: 500;
    }
    .type-badge {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      background: #f8f9fa;
      border: 2px solid #eee;
      border-radius: 8px;
      padding: 12px 16px;
    }
    .type-name {
      font-size: 18px;
      font-weight: 600;
      color: #D4537E;
    }
    .type-days {
      font-size: 14px;
      color: #666;
      border-left: 1px solid #ddd;
      padding-left: 12px;
      margin-left: 4px;
    }
    .dates-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
    }
    .total-hours {
      background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
      border-radius: 8px;
      padding: 20px;
      text-align: center;
    }
    .total-hours-value {
      font-size: 32px;
      font-weight: 700;
      color: #D4537E;
    }
    .total-hours-label {
      font-size: 12px;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-top: 4px;
    }
    .footer {
      border-top: 1px solid #eee;
      padding: 20px 30px;
      background: #fafafa;
      font-size: 12px;
      color: #999;
      text-align: center;
    }
    @media print {
      body { background: white; }
      .container { box-shadow: none; }
    }
  </style>
</head>
<body>
  <div class="container">
    <header class="header">
      <h1>Time Off Record</h1>
      <div class="subtitle">${escapeHtml(data.person)}</div>
    </header>
    
    <div class="content">
      <div class="field">
        <div class="field-label">Employee</div>
        <div class="field-value large">${escapeHtml(data.person)}</div>
      </div>
      
      <div class="field">
        <div class="field-label">Leave Type</div>
        <div class="type-badge">
          <span class="type-name">${getVacationTypeLabel(data.type)}</span>
          <span class="type-days">${data.days} day${data.days !== 1 ? 's' : ''}</span>
        </div>
      </div>
      
      <div class="dates-grid">
        <div class="field">
          <div class="field-label">Start Date</div>
          <div class="field-value">${formatDate(data.startDate)}</div>
        </div>
        <div class="field">
          <div class="field-label">End Date</div>
          <div class="field-value">${formatDate(data.endDate)}</div>
        </div>
      </div>
      
      <div class="field">
        <div class="field-label">Total Hours</div>
        <div class="total-hours">
          <div class="total-hours-value">${hours}</div>
          <div class="total-hours-label">hours (${data.days} days × 8 hours)</div>
        </div>
      </div>
    </div>
    
    <footer class="footer">
      Generated by NPD Planner • ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
    </footer>
  </div>
</body>
</html>`
}

// ─────────────────────────────────────────
// HELPERS
// ─────────────────────────────────────────

function escapeHtml(text: string): string {
  const div = document.createElement('div')
  div.textContent = text
  return div.innerHTML
}

function calculateDays(startDate: string, endDate: string): number {
  if (!startDate || !endDate) return 0
  const start = new Date(startDate)
  const end = new Date(endDate)
  if (isNaN(start.getTime()) || isNaN(end.getTime())) return 0
  const diffMs = end.getTime() - start.getTime()
  return Math.max(1, Math.ceil(diffMs / (1000 * 60 * 60 * 24)) + 1)
}

// ─────────────────────────────────────────
// TASK TO TEMPLATE DATA CONVERTERS
// ─────────────────────────────────────────

export function taskToTripData(task: Task, personName: string): TripData {
  return {
    name: task.title,
    person: personName,
    startDate: task.dateStart ? new Date(task.dateStart.toDate()).toISOString() : '',
    endDate: task.dateEnd ? new Date(task.dateEnd.toDate()).toISOString() : '',
    description: task.description || task.notes || ''
  }
}

export function taskToVacationData(
  task: Task, 
  personName: string, 
  vacationType: string
): VacationData {
  const startDate = task.dateStart ? new Date(task.dateStart.toDate()) : null
  const endDate = task.dateEnd ? new Date(task.dateEnd.toDate()) : null
  
  let days = 1
  if (startDate && endDate) {
    const diffMs = endDate.getTime() - startDate.getTime()
    days = Math.max(1, Math.ceil(diffMs / (1000 * 60 * 60 * 24)) + 1)
  }
  
  return {
    person: personName,
    type: (vacationType as VacationData['type']) || 'pto',
    days,
    startDate: startDate ? startDate.toISOString() : '',
    endDate: endDate ? endDate.toISOString() : ''
  }
}
